### ISSUE TITLE
00000001.cmd

### ISSUE THREAD

**Issue by ghost** [wwylele/3ds-save-tool#4]
Hello.After decoding 00000001.cmd(56 bytes) how to generate this line on the PC. The manual does not say this
![111](https://user-images.githubusercontent.com/35849884/56416076-78a2d880-6298-11e9-8416-828702bcac5c.jpg)
In manual
![112](https://user-images.githubusercontent.com/35849884/56416097-86585e00-6298-11e9-8e00-aedd392d5206.jpg)

**Comment by wwylele** [comment]
I don't know tbh, and as last time I heard from @d0k3, this was still a mystery that nobody understood.

**Comment by wwylele** [comment]
https://github.com/d0k3/GodMode9/issues/340

**Comment by d0k3** [comment]
There's a lot work done there atm. Maybe this can be solved by the work of multiple people?

**Comment by ghost** [comment]
Line 10-1F depends only on SDKEYY (in movable.sed) because all installed programs have one and the same line.The last line presumably depends on ncchheader(0x100-0x1FF) and SDKEYY because the same program on different consoles has a different line

**Comment by wwylele** [comment]
Can we move this to somewhere else? It is out of the repo's scope
