### ISSUE TITLE
error decrypting CECD

### ISSUE THREAD

**Issue by AVellucci** [wwylele/3ds-save-tool#7]
`./disa-extract.py ../00000000 ../Mine`
`No save type specified. Will skip CMAC verification.`
`Info: No partition B`
`Error: Wrong SAVE magic`

When trying to use the tool to extract my Mii Plaza data I get the above error. I'm not sure what I'm doing wrong, if I grab a CECD file from the web (A gSheet with many shared ones) they all work but extracting my own personal one with gm9 I get the error you see above. Any help on this would be greatly appreaciated

**Comment by wwylele** [comment]
Is your CECD data initialized? e.g. Has any 3ds application written data to it?
Does [save3ds](https://github.com/wwylele/save3ds) give a different result?

**Comment by AVellucci** [comment]
hmm, this is going to be an ordeal. save3ds seems to be a much more complicated program with less documentation for the layman. I only have my 00000000 file from 00010026 but it seems that this one needs some kind of backup of the entire NAND directory to work? with save3ds_fuse I get `Missing NAND` and there isn't really much I can see there in terms of setup other than needing fuse, no real explanation on how to get or set up the NAND stuff...

**Comment by wwylele** [comment]
You should be able to do  `save3ds_fuse --bare <the_file> --touch` to test it.
You can also send the file to me if you don't mind.

**Comment by AVellucci** [comment]
link to the file:
https://drive.google.com/file/d/1SRupMrqPKu_TuFd9RnqPjyv_vL2_4dcP/view?usp=sharing

the output of using touch, I've extracted this a few times and looking at it in hexfiend it seems to match other files minus the SP users. not sure why mine would be "corrupt"
`WARNING: After modification, you need to sign the CMAC header using other tools.`
`Out-of-bound access, caused by corrupted data`
`Error: OutOfBound`

**Comment by wwylele** [comment]
This file looks really weird:
 - My CECD file has size 0x3700000 bytes (note how this is nicely block-aligned), while this file is only 0x36FFCE9 (this is not even an even number). This suggests that some data got truncated somewhere. 
 -  all the save file should have at least one "SAVE" magic in the middle of the file, which is usually at 16-byte aligned. This file has several SAVE magic found, but none of them is aligned. Two of them has a 9 (mod 16) alignment, same as the weird file size, again suggesting truncated data.

I suggest checking whether you could be removing data when transferring the file. If you are sure that you dumped the original file, I suggest open an issue with gm9 to see if they could be dumping the file wrong.

**Comment by wwylele** [comment]
I am closing this given this is likely a corruption in the file itself. Feel free to comment and ask to reopen if you disagree.
